"""empty message

Revision ID: 6fe6f5b1ba17
Revises: ab3f0026a5e2
Create Date: 2026-01-26 21:40:55.015832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe6f5b1ba17'
down_revision: Union[str, Sequence[str], None] = 'ab3f0026a5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'user_id',
               existing_type=sa.INTEGER())
    op.add_column('budget_items', sa.Column('name', sa.String(), nullable=True))
    op.add_column('budget_items', sa.Column('fixed', sa.Boolean(), nullable=True))
    op.drop_column('budget_items', 'main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('main', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('budget_items', 'fixed')
    op.drop_column('budget_items', 'name')
    op.alter_column('budget', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
