"""empty message

Revision ID: 7a094f11d814
Revises: 5a4e78054396
Create Date: 2025-10-20 19:59:19.940786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a094f11d814'
down_revision: Union[str, Sequence[str], None] = '5a4e78054396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('planned_value', sa.Float(), nullable=True),
    sa.Column('real_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_items')
    op.drop_table('budget')
    # ### end Alembic commands ###
