"""empty message

Revision ID: ab3f0026a5e2
Revises: 7a094f11d814
Create Date: 2026-01-26 20:41:17.836283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3f0026a5e2'
down_revision: Union[str, Sequence[str], None] = '7a094f11d814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('user_id', sa.Integer()))
    op.create_foreign_key(None, 'budget', 'users', ['user_id'], ['id'])
    op.add_column('budget_items', sa.Column('fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'main')
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_column('budget', 'user_id')
    # ### end Alembic commands ###
