"""empty message

Revision ID: f28d58a83253
Revises: 57d6674ec2f0
Create Date: 2025-08-08 20:47:31.668673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28d58a83253'
down_revision: Union[str, Sequence[str], None] = '57d6674ec2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'models', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('users_model_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_model_id_fkey'), 'users', 'models', ['model_id'], ['id'])
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'user_id')
    # ### end Alembic commands ###
