version: '3.9'

# NOTE: move passwords to env variable

services:
  postgresql:
    container_name: tracker-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tracker-wystatkow
      POSTGRES_PASSWORD: 12345678
    ports:
     - "2323:5432"
  pgadmin:
    container_name: tracker-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "50600:80"
